# Generated by Django 4.2.11 on 2026-04-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_email_verified_customuser_phone_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_verified',
            field=models.BooleanField(default=True, help_text='Phone verification (auto-verified)'),
        ),
    ]
