# Generated by Django 4.2.11 on 2026-04-06

from django.db import migrations, models


def set_blank_phone_to_null(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(phone='').update(phone=None)


def set_null_phone_to_blank(apps, schema_editor):
    CustomUser = apps.get_model('users', 'CustomUser')
    CustomUser.objects.filter(phone__isnull=True).update(phone='')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_change_phone_verified_default'),
    ]

    operations = [
        migrations.RunPython(set_blank_phone_to_null, set_null_phone_to_blank),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(
                max_length=20,
                blank=True,
                null=True,
                unique=True,
                default=None,
                help_text='Phone number for delivery updates',
            ),
        ),
    ]
