# Generated by Django 6.0.1 on 2026-05-05 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_require_unique_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='URL to navigate when notification is clicked', max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='conversation_id',
            field=models.PositiveIntegerField(blank=True, help_text='Related chat conversation ID', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('general', 'General'), ('order', 'Order'), ('chat', 'Chat'), ('product', 'Product'), ('promotion', 'Promotion')], db_index=True, default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='order_id',
            field=models.PositiveIntegerField(blank=True, help_text='Related order ID', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='product_id',
            field=models.PositiveIntegerField(blank=True, help_text='Related product ID', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-created_at'], name='users_notif_user_id_c37f16_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='users_notif_user_id_1be17e_idx'),
        ),
    ]
