# Generated by Django 6.0.1 on 2026-08-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='activity',
            name='activity_user_time_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_email_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_role_idx',
        ),
        migrations.RemoveIndex(
            model_name='customuser',
            name='user_email_verified_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notif_user_read_idx',
        ),
        migrations.RemoveIndex(
            model_name='otpverification',
            name='otp_email_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='otpverification',
            name='otp_expires_idx',
        ),
    ]
