# Generated by Django 6.0.7 on 2026-08-24 09:48

import django.db.models.deletion
import secrets
from django.conf import settings
from django.db import migrations, models


def populate_security_questions(apps, schema_editor):
	SecurityQuestion = apps.get_model('users', 'SecurityQuestion')
	questions = [
		('pet_name', 'What was the name of your first pet?'),
		('birth_city', 'In what city were you born?'),
		('school_name', 'What was the name of your elementary school?'),
		('mother_maiden', "What is your mother's maiden name?"),
		('first_car', 'What was the make and model of your first car?'),
		('fav_teacher', 'Who was your favorite teacher?'),
		('birth_month', 'In what month was your father born?'),
		('childhood_friend', 'What was the name of your childhood best friend?'),
	]
	for key, text in questions:
		SecurityQuestion.objects.get_or_create(question_key=key, defaults={'question_text': text})


def reverse_populate_security_questions(apps, schema_editor):
	SecurityQuestion = apps.get_model('users', 'SecurityQuestion')
	SecurityQuestion.objects.all().delete()


def backfill_account_ids(apps, schema_editor):
	CustomUser = apps.get_model('users', 'CustomUser')
	for user in CustomUser.objects.filter(account_id__isnull=True):
		account_id = secrets.token_urlsafe(6).upper()[:8]
		while CustomUser.objects.filter(account_id=account_id).exists():
			account_id = secrets.token_urlsafe(6).upper()[:8]
		user.account_id = account_id
		user.save(update_fields=['account_id'])


def reverse_backfill_account_ids(apps, schema_editor):
	CustomUser = apps.get_model('users', 'CustomUser')
	CustomUser.objects.update(account_id=None)


class Migration(migrations.Migration):

	dependencies = [
		('users', '0014_remove_activity_activity_user_time_idx_and_more'),
	]

	operations = [
		migrations.CreateModel(
			name='SecurityQuestion',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('question_key', models.CharField(choices=[('pet_name', 'What was the name of your first pet?'), ('birth_city', 'In what city were you born?'), ('school_name', 'What was the name of your elementary school?'), ('mother_maiden', "What is your mother's maiden name?"), ('first_car', 'What was the make and model of your first car?'), ('fav_teacher', 'Who was your favorite teacher?'), ('birth_month', 'In what month was your father born?'), ('childhood_friend', 'What was the name of your childhood best friend?')], max_length=50, unique=True)),
				('question_text', models.CharField(max_length=255)),
			],
			options={
				'ordering': ['question_key'],
			},
		),
		migrations.AddField(
			model_name='customuser',
			name='account_id',
			field=models.CharField(blank=True, db_index=True, help_text='Cryptographic random account identifier', max_length=12, null=True, unique=True),
		),
		migrations.CreateModel(
			name='SecurityAnswer',
			fields=[
				('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('answer_hash', models.CharField(help_text='Hashed answer (one-way)', max_length=255)),
				('created_at', models.DateTimeField(auto_now_add=True)),
				('updated_at', models.DateTimeField(auto_now=True)),
				('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_answers', to=settings.AUTH_USER_MODEL)),
				('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.securityquestion')),
			],
			options={
				'ordering': ['user', 'question'],
				'unique_together': {('user', 'question')},
			},
		),
		migrations.RunPython(populate_security_questions, reverse_populate_security_questions),
		migrations.RunPython(backfill_account_ids, reverse_backfill_account_ids),
	]
