# Generated by Django 6.0.7 on 2026-08-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_securityquestion_customuser_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otpverification',
            name='otp_code',
        ),
        migrations.AddField(
            model_name='otpverification',
            name='otp_code_hash',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
