# Generated by Django 6.0.7 on 2026-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_hash_otp_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks users created by the sample data tool'),
        ),
    ]
