# Generated by Django 6.0.7 on 2026-09-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_add_is_sample_fields'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['is_resolved', '-created_at'], name='feedback_resolved_created'),
        ),
    ]
