# Generated by Django 6.0.1 on 2026-09-05 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_feedback_feedback_resolved_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityquestion',
            name='question_key',
            field=models.CharField(choices=[('pet_name', 'What is the name of your first pet?'), ('fav_color', 'What is your favorite color?'), ('best_friend', 'What is the name of your best friend?'), ('fav_food', 'What is your favorite food?'), ('fav_book', 'What is your favorite book or author?'), ('childhood_hero', 'What is the name of your childhood hero?'), ('childhood_street', 'What is the name of the street you grew up on?'), ('fav_movie', 'What is your favorite movie of all time?'), ('first_teacher', 'What is the name of your first teacher?'), ('fav_vacation', 'What is your favorite vacation destination?'), ('fav_childhood_memory', 'What is your favorite childhood memory?'), ('fav_athlete', 'What is the name of your favorite athlete or sports team?'), ('fav_restaurant', 'What is the name of your favorite restaurant or meal?'), ('dream_job', 'What is your dream job or career?'), ('first_school', 'What is the name of the first school you attended?'), ('fav_song', 'What is your favorite song or artist?'), ('first_car', 'What is the name of your first car?'), ('fav_tradition', 'What is your favorite family tradition?'), ('closest_relative', 'What is the name of your closest relative?'), ('mother_maiden', "What is your mother's maiden name?"), ('birth_city', 'In what city were you born?'), ('school_name', 'What was the name of your elementary school?'), ('fav_teacher', 'Who was your favorite teacher?'), ('birth_month', 'In what month was your father born?'), ('childhood_friend', 'What was the name of your childhood best friend?')], max_length=50, unique=True),
        ),
    ]
