services:
  - type: web
    name: olid-stores
    env: python
    plan: starter
    region: oregon
    buildCommand: pip install -r requirements.txt && python manage.py migrate --noinput && python manage.py fix_delivery_fee_totals && python manage.py axes_reset && python manage.py collectstatic --noinput
    startCommand: gunicorn e_stores.wsgi:application
    healthCheckPath: /
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "olidstores.onrender.com"
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_STORAGE_BUCKET
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: SENDGRID_SENDER_EMAIL
        sync: false
      - key: REDIS_URL
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
