# Generated by Django 4.2.11 on 2026-01-25 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='map_embed',
            field=models.TextField(blank=True, help_text='Embed code for Google Maps or similar'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
