# Generated by Django 4.2.11 on 2026-01-25 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitecontent_map_embed_sitecontent_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
