# Generated by Django 4.2.11 on 2026-01-25 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitecontent_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='social_links',
            field=models.TextField(blank=True, help_text='Comma-separated list of social media links (e.g. https://twitter.com/yourpage, https://facebook.com/yourpage)'),
        ),
    ]
