# Generated by Django 4.2.11 on 2026-01-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitecontent_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='social',
            field=models.JSONField(blank=True, default=dict, help_text='JSON object for social handles, e.g. {"twitter":"@you", "instagram":"you", "whatsapp":"080..."}', null=True),
        ),
    ]
