# Generated by Django 4.2.11 on 2026-01-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_bannerimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannerimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='banners/thumbs/'),
        ),
    ]
