# Generated by Django 4.2.11 on 2026-01-26 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_heroimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroimage',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='hero/thumbs/'),
        ),
    ]
