# Generated by Django 4.2.11 on 2026-01-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_teammember_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='delivery_fee_24h',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for 24-hour delivery (admin editable)', max_digits=10),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='delivery_fee_2d',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for 2-day delivery (admin editable)', max_digits=10),
        ),
    ]
