# Generated by Django 4.2.11 on 2026-02-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_sitecontent_delivery_fee_24h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='background_style',
            field=models.CharField(choices=[('gradient_blue', 'Dark Blue Gradient (Default)'), ('gradient_purple', 'Purple Gradient'), ('gradient_orange', 'Orange Sunset Gradient'), ('gradient_green', 'Green Gradient'), ('animated_gradient', 'Animated Rainbow Gradient'), ('particles', 'Particle Animation'), ('waves', 'Animated Waves'), ('video', 'Video Background (Upload video file)')], default='gradient_blue', help_text='Choose background style for homepage banner', max_length=50),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='background_video',
            field=models.FileField(blank=True, help_text='Upload video for video background (MP4 format recommended)', null=True, upload_to='backgrounds/'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='key',
            field=models.CharField(choices=[('about', 'About Page'), ('contact', 'Contact Page'), ('homepage_banner', 'Homepage Banner'), ('checkout', 'Checkout Section')], max_length=50, unique=True),
        ),
    ]
