# Generated by Django 4.2.11 on 2026-02-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_banner_background_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='announcement_text',
            field=models.TextField(blank=True, help_text="Top banner announcement text (e.g. 'Free shipping on orders over ₦15,000 | Use code DFLOW10 for 10% off')"),
        ),
    ]
