# Generated by Django 4.2.11 on 2026-02-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_announcement_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='account_name',
            field=models.CharField(blank=True, help_text='Account holder name for manual transfers', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='account_number',
            field=models.CharField(blank=True, help_text='Account number for manual bank transfers', max_length=50),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for manual transfer payments (e.g. GTBank, Access Bank)', max_length=100),
        ),
    ]
