# Generated by Django 4.2.11 on 2026-04-03 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_bank_transfer_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='business_hours',
            field=models.TextField(blank=True, help_text='Business hours (e.g. Mon-Fri: 9AM-6PM, Sat: 10AM-4PM)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='facebook_handle',
            field=models.CharField(blank=True, help_text='Facebook page/handle or full URL', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='favicon',
            field=models.ImageField(blank=True, help_text='Favicon for browser tabs (32x32 or 64x64 ICO/PNG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='footer_text',
            field=models.TextField(blank=True, help_text='Custom footer text (copyright, legal info, etc.)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='free_shipping_threshold',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Order amount for free shipping (0 = disabled)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='instagram_handle',
            field=models.CharField(blank=True, help_text='Instagram handle (e.g. yourhandle) or full URL', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO meta description for this page (150-160 characters recommended)'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=500),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='return_policy_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days for returns/exchanges'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='site_logo',
            field=models.ImageField(blank=True, help_text='Your store logo (recommended: 200x60px or SVG)', null=True, upload_to='site/'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='site_name',
            field=models.CharField(blank=True, help_text='Your store/site name displayed in header and emails', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='site_tagline',
            field=models.CharField(blank=True, help_text='A short tagline or slogan for your store', max_length=300),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='store_address',
            field=models.TextField(blank=True, help_text='Physical store address for contact page and footer'),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='tiktok_handle',
            field=models.CharField(blank=True, help_text='TikTok handle or full URL', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='twitter_handle',
            field=models.CharField(blank=True, help_text='Twitter handle (e.g. @yourhandle) or full URL', max_length=100),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number (e.g. +2348012345678) or wa.me link', max_length=30),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='youtube_handle',
            field=models.CharField(blank=True, help_text='YouTube channel URL', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='background_style',
            field=models.CharField(choices=[('gradient_blue', 'Dark Blue Gradient (Default)'), ('gradient_purple', 'Purple Gradient'), ('gradient_orange', 'Orange Sunset Gradient'), ('gradient_green', 'Green Gradient'), ('animated_gradient', 'Animated Rainbow Gradient'), ('particles', 'Particle Animation'), ('waves', 'Animated Waves'), ('sunset_blur', 'Sunset Blur (Warm Orbs)'), ('neon_pulse', 'Neon Pulse (Animated Glow)'), ('stellar_night', 'Starlit Night (Stars + Depth)'), ('video', 'Video Background (Upload video file)')], default='gradient_blue', help_text='Choose background style for homepage banner', max_length=50),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='key',
            field=models.CharField(choices=[('about', 'About Page'), ('contact', 'Contact Page'), ('homepage_banner', 'Homepage Banner'), ('checkout', 'Checkout Section'), ('site_settings', 'Site Settings'), ('faq', 'FAQ Page'), ('privacy', 'Privacy Policy'), ('terms', 'Terms & Conditions')], max_length=50, unique=True),
        ),
    ]
