# Generated by Django 4.2.11 on 2026-04-03 15:05

from django.db import migrations


# Default FAQ content (plain text)
DEFAULT_FAQ_CONTENT = '''How do I place an order?
Browse our product catalog, select items you wish to purchase, and add them to your cart. Once you're ready, proceed to checkout, fill in your shipping details, choose your payment method, and complete your order. You'll receive a confirmation email with your order details.

What payment methods are accepted?
We accept multiple payment methods including Paystack (credit/debit cards and bank transfers), Manual Bank Transfer with receipt upload, and Pay on Delivery for eligible orders. All online payments are secured with SSL encryption.

How do I track my order?
Log into your account and visit your Dashboard. Navigate to the Orders section to view your complete order history, current status, and tracking information. You'll also receive email updates at each stage of your order's journey.

What are the delivery times?
Standard Delivery: 3-7 business days within Lagos
24-Hour Express: Next-day delivery for select products (additional fee applies)
Nationwide: 5-14 business days depending on your location
Free delivery on orders above ₦50,000!

What is your return policy?
You can return items within 14 days of delivery. Items must be unused, in original packaging with tags attached. Refunds are processed within 7-14 business days after return approval. Please note that return shipping costs are the customer's responsibility unless the product is defective.

How do I contact support?
You can reach our customer support team through multiple channels: Use our Contact Page for inquiries, email us at support@e-stores.com, or call our hotline during business hours. We typically respond within 24 hours.

Is Pay on Delivery available?
Yes! Pay on Delivery is available for orders under ₦100,000 within Lagos. You can inspect your items before making payment. Please note that additional delivery fees may apply for POD orders, and repeated order rejections may result in service restrictions.

Is my payment information secure?
Absolutely! We use industry-standard SSL encryption to protect all transactions. We never store your complete card details on our servers. All payments are processed through secure, PCI-compliant payment gateways like Paystack.
'''

# Default Privacy Policy content (plain text)
DEFAULT_PRIVACY_CONTENT = '''Our Commitment to Your Privacy
At E-Stores, your privacy is of paramount importance to us. We are committed to protecting your personal information and ensuring transparency about how we collect, use, and safeguard your data. We collect only the information necessary to process your orders and improve your shopping experience. We never share your data with third parties without your explicit consent.

Information We Collect
We collect the following types of information:
- Personal Information: Name, email address, phone number, and shipping address
- Order Information: Products purchased, order history, and payment details (encrypted)
- Technical Data: IP address, browser type, device information, and cookies
- Communication Data: Feedback, reviews, and customer support inquiries

How We Use Your Information
Your information is used to:
- Process and fulfill your orders
- Communicate order status and shipping updates
- Provide customer support and respond to inquiries
- Improve our website and shopping experience
- Send promotional offers (with your consent)
- Comply with legal obligations

Data Security
We implement industry-standard security measures to protect your personal information from unauthorized access, disclosure, alteration, or destruction. All payment transactions are encrypted using secure SSL technology.

Your Rights
You have the right to:
- Access your personal data
- Request correction of inaccurate data
- Request deletion of your data
- Opt-out of marketing communications
- Lodge a complaint with supervisory authorities

Contact Us
If you have any questions about this Privacy Policy, please contact us through our Contact Page or email us at privacy@e-stores.com.
'''

# Default Terms & Conditions content (plain text)
DEFAULT_TERMS_CONTENT = '''Agreement to Terms
By accessing and using E-Stores, you agree to be bound by these Terms and Conditions. If you do not agree with any part of these terms, please do not use our services. Please read these terms carefully before making any purchase. Your order constitutes acceptance of these terms.

Product Information
We strive to provide accurate product descriptions, images, and pricing. However:
- Product colors may vary slightly from images due to screen settings
- Prices are subject to change without prior notice
- Products are subject to availability
- We reserve the right to limit order quantities

Order Processing & Payment
All orders are subject to acceptance and availability. We accept the following payment methods:
- Paystack: Secure card payments and bank transfers
- Manual Bank Transfer: With receipt upload verification
- Pay on Delivery: Available for eligible orders
Orders are not confirmed until payment is received and verified. We reserve the right to cancel orders for non-payment.

Delivery Policy
Delivery Times:
- Standard Delivery: 3-7 business days within Lagos
- 24-Hour Delivery: Available for select products with additional fee
- Nationwide Delivery: 5-14 business days depending on location
Delivery Fees: Calculated based on location and order value. Free delivery on orders above ₦50,000.

Return & Refund Policy
We want you to be completely satisfied with your purchase.
- Return Window: 14 days from delivery date
- Condition: Items must be unused, in original packaging with tags attached
- Refund Processing: 7-14 business days after return approval
- Return Shipping: Customer responsibility unless product is defective
Non-Returnable Items: Perishable goods, custom-made products, and intimate items.

Pay on Delivery Terms
- Available for orders under ₦100,000 within Lagos
- Customers must inspect items before payment
- Refusal to accept delivery may result in service restrictions
- Additional delivery fee may apply for POD orders

User Conduct
Users agree not to:
- Provide false or misleading information
- Use the platform for fraudulent purposes
- Interfere with platform operations
- Violate any applicable laws or regulations

Limitation of Liability
E-Stores shall not be liable for indirect, incidental, or consequential damages arising from:
- Product use or inability to use products
- Delivery delays due to unforeseen circumstances
- Third-party service failures (payment gateways, courier services)

Modifications to Terms
We reserve the right to modify these Terms and Conditions at any time. Changes will be effective immediately upon posting. Continued use of our services constitutes acceptance of modified terms.

Contact Information
For questions about these Terms and Conditions, please contact us:
Email: support@e-stores.com
Phone: +234-XXX-XXX-XXXX
'''


def populate_default_content(apps, schema_editor):
    """Populate FAQ, Privacy, and Terms with default content if empty."""
    SiteContent = apps.get_model('core', 'SiteContent')
    
    # FAQ
    faq, created = SiteContent.objects.get_or_create(key='faq')
    if not faq.content:
        faq.title = 'Frequently Asked Questions'
        faq.content = DEFAULT_FAQ_CONTENT.strip()
        faq.save()
    
    # Privacy Policy
    privacy, created = SiteContent.objects.get_or_create(key='privacy')
    if not privacy.content:
        privacy.title = 'Privacy Policy'
        privacy.content = DEFAULT_PRIVACY_CONTENT.strip()
        privacy.save()
    
    # Terms & Conditions
    terms, created = SiteContent.objects.get_or_create(key='terms')
    if not terms.content:
        terms.title = 'Terms & Conditions'
        terms.content = DEFAULT_TERMS_CONTENT.strip()
        terms.save()


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear the content (optional)."""
    pass  # Keep the content as is, don't clear on reverse


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_site_settings_fields'),
    ]

    operations = [
        migrations.RunPython(populate_default_content, reverse_populate),
    ]
