# Generated by Django 4.2.11 on 2026-04-03 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_populate_default_policy_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='announcement_bar_item1',
            field=models.CharField(blank=True, default='Free shipping on orders over ₦15,000', help_text='First announcement item (e.g. shipping info)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='announcement_bar_item2',
            field=models.CharField(blank=True, default='Use code OLID10 for 10% off', help_text='Second announcement item (e.g. promo code)', max_length=200),
        ),
        migrations.AddField(
            model_name='sitecontent',
            name='announcement_bar_item3',
            field=models.CharField(blank=True, default='Secure checkout guaranteed', help_text='Third announcement item (e.g. trust message)', max_length=200),
        ),
    ]
