# Generated by Django 4.2.11 on 2026-04-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_contact_message_reply_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatAutoReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('orders', 'Orders & Delivery'), ('payment', 'Payment & Checkout'), ('returns', 'Returns & Refunds'), ('products', 'Products & Stock'), ('account', 'Account & Login'), ('general', 'General')], default='general', max_length=30)),
                ('question', models.CharField(help_text='Short label shown in admin (e.g. "Where is my order?")', max_length=300)),
                ('keywords', models.TextField(help_text='Comma-separated trigger words/phrases (e.g. track,where is my order,delivery status)')),
                ('response', models.TextField(help_text='The message the bot will send back to the customer')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='Higher number = checked first. Useful for overriding generic rules.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Chat Auto-Reply',
                'verbose_name_plural': 'Chat Auto-Replies',
                'ordering': ['-priority', 'category', 'question'],
            },
        ),
    ]
