# Generated by Django 6.0.1 on 2026-05-15 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_newsletter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='background_style',
            field=models.CharField(choices=[('gradient_blue', 'Dark Blue Gradient (Default)'), ('gradient_purple', 'Purple Gradient'), ('gradient_orange', 'Orange Sunset Gradient'), ('gradient_green', 'Green Gradient'), ('gradient_black', 'Pure Black'), ('animated_gradient', 'Animated Rainbow Gradient'), ('particles', 'Particle Animation'), ('waves', 'Animated Waves'), ('sunset_blur', 'Sunset Blur (Warm Orbs)'), ('neon_pulse', 'Neon Pulse (Animated Glow)'), ('stellar_night', 'Starlit Night (Stars + Depth)'), ('video', 'Video Background (Upload video file)')], default='gradient_blue', help_text='Choose background style for homepage banner', max_length=50),
        ),
    ]
