# Generated by Django 6.0.7 on 2026-08-30 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_sitecontent_background_style'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
