# Generated by Django 6.0.7 on 2026-09-01 22:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_delete_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chatconversation',
            index=models.Index(fields=['status', '-updated_at'], name='chatconv_status_updated'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='chatmsg_conv_created'),
        ),
        migrations.AddIndex(
            model_name='chatmessage',
            index=models.Index(fields=['sender_type', 'is_read'], name='chatmsg_sender_read'),
        ),
    ]
