# Generated by Django 6.1.1 on 2026-09-26 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_homepage_cms_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='delivery_fee_24h',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for 2-3 day delivery (admin editable)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='2-3 Day Delivery Fee'),
        ),
        migrations.AlterField(
            model_name='sitecontent',
            name='delivery_fee_2d',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for 5-day delivery (admin editable)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='5-Day Delivery Fee'),
        ),
    ]
