# Generated by Django 4.2.11 on 2026-01-25 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('order_count', models.IntegerField(default=0)),
                ('completed_order_count', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('buyers', models.IntegerField(default=0)),
                ('revenue_by_category', models.JSONField(blank=True, default=dict, null=True)),
                ('top_products', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
