# Generated by Django 4.2.11 on 2026-01-25 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt',
            field=models.FileField(blank=True, help_text='Upload payment receipt for manual bank transfer', null=True, upload_to='receipts/'),
        ),
    ]
