# Generated by Django 4.2.11 on 2026-01-26 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_order_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='paystack', max_length=50)),
                ('event_type', models.CharField(max_length=100)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('payload', models.JSONField()),
                ('headers', models.JSONField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('last_attempt', models.DateTimeField(blank=True, null=True)),
                ('response_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
