# Generated by Django 4.2.11 on 2026-01-27 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_webhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee_24h', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for 24-hour delivery', max_digits=10)),
                ('delivery_fee_2d', models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for 2-day delivery', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Checkout Setting',
                'verbose_name_plural': 'Checkout Settings',
            },
        ),
    ]
