# Generated by Django 4.2.11 on 2026-01-27 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_checkoutsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('24h', '24-hour'), ('2d', '2-day')], default='2d', max_length=10),
        ),
    ]
