# Generated by Django 4.2.11 on 2026-02-08 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Payment channel: card, bank, ussd, qr, etc.', max_length=50, null=True),
        ),
    ]
