# Generated by Django 6.0.1 on 2026-04-05 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_delivered_at_order_shipped_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_paystack', models.BooleanField(default=True, help_text='Allow Paystack checkout when the public key is configured.')),
                ('enable_manual_transfer', models.BooleanField(default=True, help_text='Allow manual bank transfer checkout.')),
                ('enable_pay_on_delivery', models.BooleanField(default=False, help_text='Allow pay-on-delivery checkout option.')),
                ('pay_on_delivery_max', models.DecimalField(decimal_places=2, default=100000.0, help_text='Maximum order total eligible for pay on delivery.', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Selected payment method for this order (paystack, manual, pay_on_delivery)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
