# Generated by Django 6.0.1 on 2026-05-08 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='OrderAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('cancel', 'Cancelled'), ('delete', 'Deleted'), ('status_change', 'Status Changed'), ('stock_reversal', 'Stock Reversal'), ('update', 'Updated')], max_length=20)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='Dict of field changes with [old_value, new_value]')),
                ('stock_reversed', models.JSONField(blank=True, default=dict, help_text='Stock reversals: {product_id: qty, variant_id: qty}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order', '-created_at'], name='orderaudit_order_created')],
            },
        ),
    ]
