# Generated by Django 6.0.1 on 2026-08-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='cart',
            name='cart_session_idx',
        ),
        migrations.RemoveIndex(
            model_name='cartitem',
            name='cartitem_cart_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_deleted_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_payment_method_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_ref_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymenttransaction',
            name='payment_order_date_idx',
        ),
    ]
