# Generated by Django 6.0.7 on 2026-08-24 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_cart_cart_user_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, db_index=True, help_text='Carrier tracking number for this order', max_length=100, null=True),
        ),
    ]
