# Generated by Django 6.0.7 on 2026-08-27 03:43

from django.db import migrations, models


def backfill_order_numbers(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    from django.utils import timezone
    import random
    import string
    
    orders = Order.objects.filter(number__isnull=True).order_by('id')
    year = timezone.now().year
    prefix = f"EST-{year}-"
    
    # Get the current max sequence
    existing = Order.objects.filter(number__startswith=prefix).exclude(number__isnull=True).order_by('-number').first()
    if existing and existing.number:
        try:
            seq = int(existing.number.split('-')[-1]) + 1
        except (ValueError, IndexError):
            seq = 1
    else:
        seq = 1
    
    for order in orders:
        order.number = f"{prefix}{seq:04d}"
        seq += 1
        order.save(update_fields=['number'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_add_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, help_text='Human-friendly order number (e.g. EST-2026-0001)', max_length=30, null=True, unique=True),
        ),
        migrations.RunPython(backfill_order_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(help_text='Human-friendly order number (e.g. EST-2026-0001)', max_length=30, unique=True),
        ),
    ]
