# Generated by Django 6.0.7 on 2026-08-27 03:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_add_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Token for public order confirmation page access'),
        ),
        migrations.AlterField(
            model_name='order',
            name='number',
            field=models.CharField(blank=True, help_text='Human-friendly order number (e.g. EST-2026-0001)', max_length=30, unique=True),
        ),
    ]
