# Generated by Django 6.0.7 on 2026-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_add_confirmation_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks orders created by the sample data tool'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_sample',
            field=models.BooleanField(default=False, help_text='Marks order items created by the sample data tool'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='is_sample',
            field=models.BooleanField(default=False, help_text='Marks payment transactions created by the sample data tool'),
        ),
    ]
