# Generated by Django 6.1.1 on 2026-09-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_add_order_composite_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='order',
            name='order_deleted_status',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='order_deleted_status_created',
        ),
        migrations.AlterField(
            model_name='checkoutsettings',
            name='delivery_fee_24h',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for 2-3 day delivery', max_digits=10, verbose_name='2-3 Day Delivery Fee'),
        ),
        migrations.AlterField(
            model_name='checkoutsettings',
            name='delivery_fee_2d',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Delivery fee for 5-day delivery', max_digits=10, verbose_name='5-Day Delivery Fee'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_option',
            field=models.CharField(choices=[('24h', '2-3 Days'), ('2d', '5 Days')], default='2d', max_length=10),
        ),
    ]
