# Generated by Django 4.2.11 on 2026-01-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_category_is_editable_product_is_editable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['id']},
        ),
    ]
