# Generated by Django 6.0.1 on 2026-08-24 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='category',
            name='category_slug_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_price_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_stock_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_cat_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='product',
            name='product_sample_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='review_prod_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='productreview',
            name='review_rating_idx',
        ),
    ]
