# Generated by Django 6.0.7 on 2026-09-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_category_category_slug_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_sample',
            field=models.BooleanField(db_index=True, default=False, help_text='Marks categories created by the sample data tool'),
        ),
    ]
